// Generated by gencpp from file messagefiles/ErrorMessages.msg
// DO NOT EDIT!


#ifndef MESSAGEFILES_MESSAGE_ERRORMESSAGES_H
#define MESSAGEFILES_MESSAGE_ERRORMESSAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <messagefiles/ErrorMessage.h>

namespace messagefiles
{
template <class ContainerAllocator>
struct ErrorMessages_
{
  typedef ErrorMessages_<ContainerAllocator> Type;

  ErrorMessages_()
    : header()
    , error_messages()  {
    }
  ErrorMessages_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , error_messages(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::messagefiles::ErrorMessage_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::messagefiles::ErrorMessage_<ContainerAllocator> >::other >  _error_messages_type;
  _error_messages_type error_messages;





  typedef boost::shared_ptr< ::messagefiles::ErrorMessages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messagefiles::ErrorMessages_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorMessages_

typedef ::messagefiles::ErrorMessages_<std::allocator<void> > ErrorMessages;

typedef boost::shared_ptr< ::messagefiles::ErrorMessages > ErrorMessagesPtr;
typedef boost::shared_ptr< ::messagefiles::ErrorMessages const> ErrorMessagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messagefiles::ErrorMessages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messagefiles::ErrorMessages_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messagefiles::ErrorMessages_<ContainerAllocator1> & lhs, const ::messagefiles::ErrorMessages_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.error_messages == rhs.error_messages;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messagefiles::ErrorMessages_<ContainerAllocator1> & lhs, const ::messagefiles::ErrorMessages_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messagefiles

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messagefiles::ErrorMessages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messagefiles::ErrorMessages_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagefiles::ErrorMessages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagefiles::ErrorMessages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagefiles::ErrorMessages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagefiles::ErrorMessages_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messagefiles::ErrorMessages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f81dd57509bac9737bd49bf8274d3e14";
  }

  static const char* value(const ::messagefiles::ErrorMessages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf81dd57509bac973ULL;
  static const uint64_t static_value2 = 0x7bd49bf8274d3e14ULL;
};

template<class ContainerAllocator>
struct DataType< ::messagefiles::ErrorMessages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messagefiles/ErrorMessages";
  }

  static const char* value(const ::messagefiles::ErrorMessages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messagefiles::ErrorMessages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ErrorMessage[] error_messages\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: messagefiles/ErrorMessage\n"
"# 错误码\n"
"int32 error_code\n"
"# 错误等级 0：Normal 1：info 2：warn 3：error\n"
"uint8 error_level\n"
"# 错误描述\n"
"string error_description\n"
;
  }

  static const char* value(const ::messagefiles::ErrorMessages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messagefiles::ErrorMessages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.error_messages);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorMessages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messagefiles::ErrorMessages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messagefiles::ErrorMessages_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "error_messages[]" << std::endl;
    for (size_t i = 0; i < v.error_messages.size(); ++i)
    {
      s << indent << "  error_messages[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::messagefiles::ErrorMessage_<ContainerAllocator> >::stream(s, indent + "    ", v.error_messages[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGEFILES_MESSAGE_ERRORMESSAGES_H
