// Generated by gencpp from file messagefiles/ReflectorPoints.msg
// DO NOT EDIT!


#ifndef MESSAGEFILES_MESSAGE_REFLECTORPOINTS_H
#define MESSAGEFILES_MESSAGE_REFLECTORPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <messagefiles/Point2D.h>

namespace messagefiles
{
template <class ContainerAllocator>
struct ReflectorPoints_
{
  typedef ReflectorPoints_<ContainerAllocator> Type;

  ReflectorPoints_()
    : points()  {
    }
  ReflectorPoints_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::messagefiles::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::messagefiles::Point2D_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::messagefiles::ReflectorPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messagefiles::ReflectorPoints_<ContainerAllocator> const> ConstPtr;

}; // struct ReflectorPoints_

typedef ::messagefiles::ReflectorPoints_<std::allocator<void> > ReflectorPoints;

typedef boost::shared_ptr< ::messagefiles::ReflectorPoints > ReflectorPointsPtr;
typedef boost::shared_ptr< ::messagefiles::ReflectorPoints const> ReflectorPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messagefiles::ReflectorPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messagefiles::ReflectorPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messagefiles::ReflectorPoints_<ContainerAllocator1> & lhs, const ::messagefiles::ReflectorPoints_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messagefiles::ReflectorPoints_<ContainerAllocator1> & lhs, const ::messagefiles::ReflectorPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messagefiles

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messagefiles::ReflectorPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagefiles::ReflectorPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagefiles::ReflectorPoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f02263beef99aa03117a577a3eb879d";
  }

  static const char* value(const ::messagefiles::ReflectorPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f02263beef99aa0ULL;
  static const uint64_t static_value2 = 0x3117a577a3eb879dULL;
};

template<class ContainerAllocator>
struct DataType< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messagefiles/ReflectorPoints";
  }

  static const char* value(const ::messagefiles::ReflectorPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point2D[] points\n"
"\n"
"================================================================================\n"
"MSG: messagefiles/Point2D\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::messagefiles::ReflectorPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReflectorPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messagefiles::ReflectorPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messagefiles::ReflectorPoints_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::messagefiles::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGEFILES_MESSAGE_REFLECTORPOINTS_H
