// Generated by gencpp from file messagefiles/savemapRequest.msg
// DO NOT EDIT!


#ifndef MESSAGEFILES_MESSAGE_SAVEMAPREQUEST_H
#define MESSAGEFILES_MESSAGE_SAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messagefiles
{
template <class ContainerAllocator>
struct savemapRequest_
{
  typedef savemapRequest_<ContainerAllocator> Type;

  savemapRequest_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  savemapRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::messagefiles::savemapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messagefiles::savemapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct savemapRequest_

typedef ::messagefiles::savemapRequest_<std::allocator<void> > savemapRequest;

typedef boost::shared_ptr< ::messagefiles::savemapRequest > savemapRequestPtr;
typedef boost::shared_ptr< ::messagefiles::savemapRequest const> savemapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messagefiles::savemapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messagefiles::savemapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messagefiles::savemapRequest_<ContainerAllocator1> & lhs, const ::messagefiles::savemapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messagefiles::savemapRequest_<ContainerAllocator1> & lhs, const ::messagefiles::savemapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messagefiles

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messagefiles::savemapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messagefiles::savemapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagefiles::savemapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagefiles::savemapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagefiles::savemapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagefiles::savemapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messagefiles::savemapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8872786d433e0c19da11fb95691e91d";
  }

  static const char* value(const ::messagefiles::savemapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8872786d433e0c1ULL;
  static const uint64_t static_value2 = 0x9da11fb95691e91dULL;
};

template<class ContainerAllocator>
struct DataType< ::messagefiles::savemapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messagefiles/savemapRequest";
  }

  static const char* value(const ::messagefiles::savemapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messagefiles::savemapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::messagefiles::savemapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messagefiles::savemapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct savemapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messagefiles::savemapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messagefiles::savemapRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGEFILES_MESSAGE_SAVEMAPREQUEST_H
