// Generated by gencpp from file messagefiles/savemap.msg
// DO NOT EDIT!


#ifndef MESSAGEFILES_MESSAGE_SAVEMAP_H
#define MESSAGEFILES_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <messagefiles/savemapRequest.h>
#include <messagefiles/savemapResponse.h>


namespace messagefiles
{

struct savemap
{

typedef savemapRequest Request;
typedef savemapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct savemap
} // namespace messagefiles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messagefiles::savemap > {
  static const char* value()
  {
    return "8170d7493ac1bfd41d6b3df794117e75";
  }

  static const char* value(const ::messagefiles::savemap&) { return value(); }
};

template<>
struct DataType< ::messagefiles::savemap > {
  static const char* value()
  {
    return "messagefiles/savemap";
  }

  static const char* value(const ::messagefiles::savemap&) { return value(); }
};


// service_traits::MD5Sum< ::messagefiles::savemapRequest> should match
// service_traits::MD5Sum< ::messagefiles::savemap >
template<>
struct MD5Sum< ::messagefiles::savemapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messagefiles::savemap >::value();
  }
  static const char* value(const ::messagefiles::savemapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messagefiles::savemapRequest> should match
// service_traits::DataType< ::messagefiles::savemap >
template<>
struct DataType< ::messagefiles::savemapRequest>
{
  static const char* value()
  {
    return DataType< ::messagefiles::savemap >::value();
  }
  static const char* value(const ::messagefiles::savemapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messagefiles::savemapResponse> should match
// service_traits::MD5Sum< ::messagefiles::savemap >
template<>
struct MD5Sum< ::messagefiles::savemapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messagefiles::savemap >::value();
  }
  static const char* value(const ::messagefiles::savemapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messagefiles::savemapResponse> should match
// service_traits::DataType< ::messagefiles::savemap >
template<>
struct DataType< ::messagefiles::savemapResponse>
{
  static const char* value()
  {
    return DataType< ::messagefiles::savemap >::value();
  }
  static const char* value(const ::messagefiles::savemapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGEFILES_MESSAGE_SAVEMAP_H
