(cl:in-package messagefiles-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEFTSPEED-VAL
          LEFTSPEED
          RIGHTSPEED-VAL
          RIGHTSPEED
          WEIGHT-VAL
          WEIGHT
          BATTERYPERCENT-VAL
          BATTERYPERCENT
          LIFTSTATUS-VAL
          LIFTSTATUS
          ELECTROMAGNET-VAL
          ELECTROMAGNET
          CHARGE-VAL
          CHARGE
          BRAKE-VAL
          BRAKE
          BACKIR-VAL
          BACKIR
          BUMPEDG-VAL
          BUMPEDG
          FRONTEMS-VAL
          FRONTEMS
          REAREMS-VAL
          REAREMS
          AGVMODE-VAL
          AGVMODE
          FRONTEMS-VAL
          FRONTEMS
          FRONTEMSREQ-VAL
          FRONTEMSREQ
          REAREMS-VAL
          REAREMS
          REAREMSREQ-VAL
          REAREMSREQ
          XMONITORERR-VAL
          XMONITORERR
          WMONITORERR-VAL
          WMONITORERR
          XSPEEDOVER-VAL
          XSPEEDOVER
          WSPEEDOVER-VAL
          WSPEEDOVER
          INITERR-VAL
          INITERR
          BATTERYPRO-VAL
          BATTERYPRO
          PNCANERR-VAL
          PNCANERR
          LEFTENCODERERR-VAL
          LEFTENCODERERR
          RIGHTENCODERERR-VAL
          RIGHTENCODERERR
          JACKENCODERERR-VAL
          JACKENCODERERR
          JACKUPLIMIT-VAL
          JACKUPLIMIT
          JACKDOWNLIMIT-VAL
          JACKDOWNLIMIT
          JACKNORESPONSE-VAL
          JACKNORESPONSE
          JACKOVERTIME-VAL
          JACKOVERTIME
          JACKWINERR-VAL
          JACKWINERR
          RESERVE-VAL
          RESERVE
))